// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vec4.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_vec4_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_vec4_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 4000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 4000000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_vec4_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_vec4_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
class vec4_proto;
class vec4_protoDefaultTypeInternal;
extern vec4_protoDefaultTypeInternal _vec4_proto_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::vec4_proto* Arena::CreateMaybeMessage<::vec4_proto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class vec4_proto PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:vec4_proto) */ {
 public:
  inline vec4_proto() : vec4_proto(nullptr) {}
  virtual ~vec4_proto();

  vec4_proto(const vec4_proto& from);
  vec4_proto(vec4_proto&& from) noexcept
    : vec4_proto() {
    *this = ::std::move(from);
  }

  inline vec4_proto& operator=(const vec4_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline vec4_proto& operator=(vec4_proto&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const vec4_proto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const vec4_proto* internal_default_instance() {
    return reinterpret_cast<const vec4_proto*>(
               &_vec4_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(vec4_proto& a, vec4_proto& b) {
    a.Swap(&b);
  }
  inline void Swap(vec4_proto* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(vec4_proto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline vec4_proto* New() const final {
    return CreateMaybeMessage<vec4_proto>(nullptr);
  }

  vec4_proto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<vec4_proto>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const vec4_proto& from);
  void MergeFrom(const vec4_proto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(vec4_proto* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "vec4_proto";
  }
  protected:
  explicit vec4_proto(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
    kWFieldNumber = 4,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 3;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // float w = 4;
  void clear_w();
  float w() const;
  void set_w(float value);
  private:
  float _internal_w() const;
  void _internal_set_w(float value);
  public:

  // @@protoc_insertion_point(class_scope:vec4_proto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float x_;
  float y_;
  float z_;
  float w_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_vec4_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// vec4_proto

// float x = 1;
inline void vec4_proto::clear_x() {
  x_ = 0;
}
inline float vec4_proto::_internal_x() const {
  return x_;
}
inline float vec4_proto::x() const {
  // @@protoc_insertion_point(field_get:vec4_proto.x)
  return _internal_x();
}
inline void vec4_proto::_internal_set_x(float value) {
  
  x_ = value;
}
inline void vec4_proto::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:vec4_proto.x)
}

// float y = 2;
inline void vec4_proto::clear_y() {
  y_ = 0;
}
inline float vec4_proto::_internal_y() const {
  return y_;
}
inline float vec4_proto::y() const {
  // @@protoc_insertion_point(field_get:vec4_proto.y)
  return _internal_y();
}
inline void vec4_proto::_internal_set_y(float value) {
  
  y_ = value;
}
inline void vec4_proto::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:vec4_proto.y)
}

// float z = 3;
inline void vec4_proto::clear_z() {
  z_ = 0;
}
inline float vec4_proto::_internal_z() const {
  return z_;
}
inline float vec4_proto::z() const {
  // @@protoc_insertion_point(field_get:vec4_proto.z)
  return _internal_z();
}
inline void vec4_proto::_internal_set_z(float value) {
  
  z_ = value;
}
inline void vec4_proto::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:vec4_proto.z)
}

// float w = 4;
inline void vec4_proto::clear_w() {
  w_ = 0;
}
inline float vec4_proto::_internal_w() const {
  return w_;
}
inline float vec4_proto::w() const {
  // @@protoc_insertion_point(field_get:vec4_proto.w)
  return _internal_w();
}
inline void vec4_proto::_internal_set_w(float value) {
  
  w_ = value;
}
inline void vec4_proto::set_w(float value) {
  _internal_set_w(value);
  // @@protoc_insertion_point(field_set:vec4_proto.w)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_vec4_2eproto
